name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 6. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # 7. Output LB DNS
      - name: Show Load Balancer DNS
        run: terraform output load_balancer_dns
